version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "${KUMA_PORT}:${KUMA_PORT}"
    volumes:
      - uptime-kuma-data:/app/data
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_SECURE=${SMTP_SECURE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${KUMA_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - kuma-net

  nginx:
    image: nginx:alpine
    container_name: kuma-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - uptime-kuma
    networks:
      - kuma-net

volumes:
  uptime-kuma-data:

networks:
  kuma-net:
    driver: bridge
